language: perl
# v0.001_100
perl:
# NEED FIX? Perl v5.8 $CPP_LINKED global symbol errors, leave disabled?
#  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"

# DEV NOTE, CORRELATION #rp11: update g++ to 4.8 for full C++11 support, including:
# -std=c++11, std::string::pop_back(), etc.

# new Docker container-based Travis-CI stack, currently disabled, does not support update-alternatives
#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#addons:
#  apt:
#    packages:
#    - g++-4.8
#    - time

# legacy Travis-CI stack, currently enabled, supports sudo & update-alternatives
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
install:
- sudo apt-get install -qq g++-4.8
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
- sudo apt-get install libgmp-dev

before_script:
# MODIFY FOLLOWING LINE TO ENABLE TEST_VERBOSE STDOUT DURING `make test`
    - export RPERL_VERBOSE=0
# UNCOMMENT FOLLOWING LINE TO ENABLE NOISY BUILD DURING `make test`; REQUIRES RPERL_VERBOSE=1 ABOVE
#    - export RPERL_DEBUG=1
# UNCOMMENT FOLLOWING LINE FOR DEV VERSIONS OF MODULES, which travis can't get from Makefile.PL
#  - cpanm -n INGY/Inline-C-0.62_03.tar.gz
# DEV NOTE, CORRELATION #rp11: following line was not necessary until before_install & install sections added
    - cpanm --quiet --installdeps --notest .

# replace default build command "perl Makefile.PL && make test"
# DEV NOTE: TEST_VERBOSE variable for ExtUtils::MakeMaker 'make' command disables suppression of stdout;
# this variable is different than, and inherits the value of, the $RPERL_VERBOSE environmental variable 
script: perl Makefile.PL && make test TEST_VERBOSE=$RPERL_VERBOSE

notifications:
  irc:
    channels:
      - "irc.perl.org#perl11"
    on_success: always
    on_failure: always
    # to enable skip_join, in IRC channel first execute `/mode -n`
    skip_join: true
    template:
      - "RPerl build %{result}. %{author} says '%{commit_message}'"
      - "%{build_url} %{compare_url}"

    # DEFAULT TEMPLATE
#      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
#      - "Change view : %{compare_url}"
#      - "Build details : %{build_url}"
